import {
  ArrowRight,
  BookOpen,
  BowlFood,
  CalendarCheck,
  CaretLeft,
  CaretRight,
  ChatCircleText,
  ChatsCircle,
  CheckCircle,
  ClipboardText,
  Clock,
  Confetti,
  EnvelopeSimple,
  Eye,
  FacebookLogo,
  ForkKnife,
  GraduationCap,
  HandHeart,
  Handshake,
  HandWaving,
  Heartbeat,
  HeartStraight,
  Image as ImageIcon,
  InstagramLogo,
  Lightning,
  LinkedinLogo,
  List,
  MapPin,
  Moon,
  NotePencil,
  PaintBrush,
  Phone,
  Plant,
  PuzzlePiece,
  ShieldCheck,
  Sparkle,
  Star,
  Sun,
  Target,
  Tree,
  UsersThree,
  WhatsappLogo,
  X,
} from "@phosphor-icons/react/dist/ssr";

import type { IconProps } from "@phosphor-icons/react";
import type { ComponentType } from "react";

const MAP: Record<string, ComponentType<IconProps>> = {
  ArrowRight,
  BookOpen,
  BowlFood,
  CalendarCheck,
  CaretLeft,
  CaretRight,
  ChatCircleText,
  ChatsCircle,
  CheckCircle,
  ClipboardText,
  Clock,
  Confetti,
  EnvelopeSimple,
  Eye,
  FacebookLogo,
  ForkKnife,
  GraduationCap,
  HandHeart,
  Handshake,
  HandWaving,
  Heartbeat,
  HeartStraight,
  ImageIcon,
  InstagramLogo,
  Lightning,
  LinkedinLogo,
  List,
  MapPin,
  Moon,
  NotePencil,
  PaintBrush,
  Phone,
  Plant,
  PuzzlePiece,
  ShieldCheck,
  Sparkle,
  Star,
  Sun,
  Target,
  Tree,
  UsersThree,
  WhatsappLogo,
  X,
};

export type IconName = keyof typeof MAP;

export function Icon({ name, ...props }: { name: string } & IconProps) {
  const Cmp = MAP[name] ?? Sparkle;
  return <Cmp {...props} />;
}
